// Pre-computes geographic data used by the site so no geo libraries ship to the client.
//   1. Land dot-matrix for the 3D globe (Natural Earth 50m, Fibonacci sphere sampling)
//   2. Regional SVG map of the Peninsular Malaysia / Singapore corridor (Natural Earth 10m)
// Run: node scripts/build-geo.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { feature } from "topojson-client";
import { geoContains, geoMercator, geoPath } from "d3-geo";

const OUT = new URL("../src/data/geo/", import.meta.url);
mkdirSync(OUT, { recursive: true });
const load = (f) => JSON.parse(readFileSync(new URL(`../node_modules/world-atlas/${f}`, import.meta.url)));

// ---------- 1. Globe land dots ----------
const SKIP_GLOBE = process.argv.includes("--region-only");
const land50 = feature(load("land-50m.json"), load("land-50m.json").objects.land);
// Split into polygons with planar lon/lat bounding boxes so each point is only tested against nearby land.
const polys = (land50.features ?? [land50]).flatMap((f) =>
  f.geometry.type === "MultiPolygon"
    ? f.geometry.coordinates.map((c) => ({ type: "Polygon", coordinates: c }))
    : [f.geometry]
).map((g) => {
  let x0 = 180, x1 = -180, y0 = 90, y1 = -90;
  for (const [x, y] of g.coordinates[0]) { x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y); }
  // polygons spanning the antimeridian (or huge) get a full-width box
  if (x1 - x0 > 300) { x0 = -180; x1 = 180; }
  return { g: { type: "Feature", geometry: g }, x0, x1, y0, y1 };
});
const onLand = (lon, lat) =>
  polys.some((p) => lon >= p.x0 && lon <= p.x1 && lat >= p.y0 && lat <= p.y1 && geoContains(p.g, [lon, lat]));
const N = SKIP_GLOBE ? 0 : 42000;
const golden = Math.PI * (3 - Math.sqrt(5));
const dots = [];
for (let i = 0; i < N; i++) {
  const y = 1 - (i / (N - 1)) * 2;
  const r = Math.sqrt(1 - y * y);
  const theta = golden * i;
  const lat = (Math.asin(y) * 180) / Math.PI;
  const lon = ((Math.atan2(Math.sin(theta) * r, Math.cos(theta) * r) * 180) / Math.PI);
  if (lat < -60) continue; // drop Antarctica for a cleaner silhouette
  if (onLand(lon, lat)) dots.push(Math.round(lat * 100), Math.round(lon * 100));
}
const buf = Buffer.from(new Int16Array(dots).buffer).toString("base64");
if (!SKIP_GLOBE) writeFileSync(
  new URL("landDots.ts", OUT),
  `// Generated by scripts/build-geo.mjs — Natural Earth 50m land, ${dots.length / 2} points.\n` +
    `// Base64 Int16 pairs: [lat*100, lon*100, ...]\nexport const LAND_DOTS_B64 =\n  "${buf}";\n`
);
console.log("globe dots:", dots.length / 2);

// ---------- 2. Regional map ----------
const W = 800, H = 860;
const bbox = { type: "Feature", geometry: { type: "MultiPoint", coordinates: [[98.3, 0.75], [104.9, 7.25]] } };
const projection = geoMercator().fitExtent([[0, 0], [W, H]], bbox);
const land10all = feature(load("land-10m.json"), load("land-10m.json").objects.land);
// Keep only polygons near the frame: far-off polygons (e.g. Antarctica) can wrap the
// clip rectangle under Mercator and flood the whole map.
const near = (ring) => ring.some(([x, y]) => x > 92 && x < 112 && y > -8 && y < 14);
const land10 = {
  type: "Feature",
  geometry: {
    type: "MultiPolygon",
    coordinates: (land10all.features ?? [land10all]).flatMap((f) =>
      f.geometry.type === "MultiPolygon" ? f.geometry.coordinates : [f.geometry.coordinates]
    ).filter((poly) => near(poly[0])),
  },
};
const countries10 = load("countries-10m.json");
const borders = feature(countries10, countries10.objects.countries);
const path = geoPath(projection.clipExtent([[-20, -20], [W + 20, H + 20]])).digits(1);
const landPath = path(land10);

// Country outlines (for subtle borders) — only countries that intersect the frame
const names = new Set(["Malaysia", "Singapore", "Thailand", "Indonesia"]);
const countryPaths = borders.features
  .filter((f) => names.has(f.properties.name) && f.properties.name !== "Indonesia")
  .map((f) => ({ name: f.properties.name, d: path(f) }));

const pt = ([lon, lat]) => projection([lon, lat]).map((v) => Math.round(v * 10) / 10);
const line = (coords) => "M" + coords.map((c) => pt(c).join(",")).join("L");

// Office positions (place-level approximations of the published office addresses)
const offices = {
  penang: pt([100.366, 5.399]),
  portklang: pt([101.44, 3.007]),
  klia: pt([101.7, 2.745]),
  langkawi: pt([99.85, 6.318]),
  singapore: pt([103.7, 1.327]),
};

// Indicative North–South highway corridor (geography, for the land haulage visual)
const landCorridor = line([
  [100.366, 5.399], [100.47, 5.2], [100.73, 4.85], [101.08, 4.6], [101.29, 4.1], [101.52, 3.68],
  [101.6, 3.25], [101.44, 3.007], [101.6, 2.95], [101.7, 2.745], [101.94, 2.73], [102.27, 2.28],
  [102.6, 2.15], [103.06, 2.01], [103.45, 1.7], [103.76, 1.47], [103.7, 1.327],
]);
// Illustrative sea lanes through the Strait of Malacca (open water waypoints)
const seaMalacca = line([
  [100.39, 5.3], [100.15, 4.6], [100.55, 3.9], [101.1, 3.15], [101.3, 2.95], [101.75, 2.35],
  [102.4, 1.95], [103.0, 1.5], [103.5, 1.18], [103.72, 1.22],
]);
const seaLangkawi = line([[100.39, 5.48], [100.1, 5.85], [99.92, 6.18], [99.86, 6.28]]);

const labels = [
  { t: "Strait of Malacca", p: pt([99.75, 3.65]), r: -38, k: "sea" },
  { t: "Andaman Sea", p: pt([98.75, 6.85]), r: 0, k: "sea" },
  { t: "South China Sea", p: pt([104.3, 3.6]), r: 0, k: "sea" },
  { t: "MALAYSIA", p: pt([102.1, 4.4]), r: 0, k: "land" },
  { t: "THAILAND", p: pt([100.9, 6.95]), r: 0, k: "land" },
  { t: "SUMATRA", p: pt([99.0, 1.4]), r: 0, k: "land" },
];

writeFileSync(
  new URL("regionMap.ts", OUT),
  `// Generated by scripts/build-geo.mjs — Natural Earth 10m land, Mercator.\n` +
    `export const REGION_VIEWBOX = { w: ${W}, h: ${H} };\n` +
    `export const REGION_LAND = ${JSON.stringify(landPath)};\n` +
    `export const REGION_COUNTRIES = ${JSON.stringify(countryPaths)};\n` +
    `export const REGION_OFFICES: Record<string, [number, number]> = ${JSON.stringify(offices)};\n` +
    `export const REGION_ROUTES = ${JSON.stringify({ landCorridor, seaMalacca, seaLangkawi })};\n` +
    `export const REGION_LABELS = ${JSON.stringify(labels)};\n`
);
console.log("region land path bytes:", landPath.length);
